require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MyKid' do
     # React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera"
  pod 'Permission-Contacts', :path => "../node_modules/react-native-permissions/ios/Contacts"
  pod 'Permission-LocationAccuracy', :path => "../node_modules/react-native-permissions/ios/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "../node_modules/react-native-permissions/ios/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "../node_modules/react-native-permissions/ios/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "../node_modules/react-native-permissions/ios/MediaLibrary"
  pod 'Permission-Microphone', :path => "../node_modules/react-native-permissions/ios/Microphone"
  pod 'Permission-PhotoLibrary', :path => "../node_modules/react-native-permissions/ios/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "../node_modules/react-native-permissions/ios/PhotoLibraryAddOnly"

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'


  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'react-native-amr', :path => '../node_modules/react-native-amr'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'
  target 'MyKidTests' do
    inherit! :complete
    # Pods for testing
  end

#  post_install do |installer|
#    react_native_post_install(installer)
#    installer.pods_project.targets.each do |target|
#      if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
#        def pod.build_type;
#        end
#      end
#    end
#  end
end
